In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [21]:
#df = pd.read_csv('/content/MNIST_train.csv')
df = pd.read_csv('/content/MNIST_test.csv')

In [22]:
df.columns

Index(['Unnamed: 0', 'index', 'labels', '0', '1', '2', '3', '4', '5', '6',
       ...
       '774', '775', '776', '777', '778', '779', '780', '781', '782', '783'],
      dtype='object', length=787)

In [23]:
df = df.drop(['Unnamed: 0', 'index'], axis=1)

In [24]:
X = df.to_numpy()

In [25]:
X.shape

(10000, 785)

In [26]:
X

array([[7, 0, 0, ..., 0, 0, 0],
       [2, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [4, 0, 0, ..., 0, 0, 0],
       [5, 0, 0, ..., 0, 0, 0],
       [6, 0, 0, ..., 0, 0, 0]])

In [27]:
y = X[:,0]

In [28]:
y

array([7, 2, 1, ..., 4, 5, 6])

In [29]:
X=X[:,1:]

In [30]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [31]:
X = X/255

In [13]:
class KNNClassifier():

  def fit(self,X,y):
    self.X = X
    self.y = y.astype(int)

  def predict(self, X, K,epsilon=1e-3):
    N = len(X)
    y_hat = np.zeros(N)

    for i in range(N):
      dist2 = np.sum((self.X-X[i])**2, axis=1)
      idxt = np.argsort(dist2)[:K]
      gamma_k = 1/(np.sqrt(dist2[idxt]+epsilon))

      y_hat[i] = np.bincount(self.y[idxt], weights = gamma_k).argmax()

    return y_hat

In [14]:
knn_instance = KNNClassifier()
knn_instance.fit(X,y)

In [1]:
y_hat = knn_instance.predict(X, K=20)

NameError: name 'knn_instance' is not defined

In [16]:
def accuracy(y,y_hat):
  return np.mean(y==y_hat)

In [18]:
accuracy(y,y_hat)
#Train: 0.9999

0.9999373315786175